# Generated by Django 5.2.7 on 2026-02-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeDetails',
            fields=[
                ('change_id', models.AutoField(primary_key=True, serialize=False)),
                ('change_number', models.CharField(max_length=100, unique=True)),
                ('title', models.TextField()),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(max_length=100)),
                ('project_type', models.CharField(max_length=100)),
                ('sub_type', models.CharField(max_length=100)),
                ('zerotouch', models.BooleanField(default=False)),
                ('startdate', models.DateTimeField(blank=True, null=True)),
                ('enddate', models.DateTimeField(blank=True, null=True)),
                ('remedy_status', models.CharField(blank=True, max_length=100, null=True)),
                ('remedy_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('change_status', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('final_status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed'), ('Partial', 'Partial'), ('Unknown', 'Unknown')], default='Unknown', max_length=20)),
            ],
            options={
                'verbose_name': 'Change Detail',
                'verbose_name_plural': 'Change Details',
                'db_table': 'change_details',
                'ordering': ['change_number'],
                'indexes': [models.Index(fields=['change_number'], name='change_deta_change__47cd43_idx')],
            },
        ),
    ]
