# Generated by Django 5.2.7 on 2026-05-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrqProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_impacting', models.BooleanField(default=False)),
                ('change_type', models.CharField(choices=[('Service / Normal Maintenance', 'Service / Normal Maintenance'), ('Customer Change', 'Customer Change'), ('Emergency Maintenance', 'Emergency Maintenance')], max_length=100)),
                ('manager_group', models.CharField(choices=[('Infra Change', 'Infra Change'), ('Client Change', 'Client Change')], max_length=100)),
                ('class1', models.CharField(choices=[('No Impact', 'No Impact'), ('Standard', 'Standard'), ('Normal', 'Normal'), ('Emergency', 'Emergency'), ('Expedited', 'Expedited')], db_column='class', max_length=100)),
                ('impact', models.CharField(choices=[('1-Extensive/Widespread', '1-Extensive/Widespread'), ('2-Significant/Large', '2-Significant/Large'), ('3-Moderate/Limited', '3-Moderate/Limited'), ('4-Minor/Localized', '4-Minor/Localized')], max_length=100)),
                ('urgency', models.CharField(choices=[('1-Critical', '1-Critical'), ('2-High', '2-High'), ('3-Medium', '3-Medium'), ('4-Low', '4-Low')], max_length=100)),
                ('risk_level', models.CharField(choices=[('Risk Level 1', 'Risk Level 1'), ('Risk Level 2', 'Risk Level 2'), ('Risk Level 3', 'Risk Level 3'), ('Risk Level 4', 'Risk Level 4'), ('Risk Level 5', 'Risk Level 5')], max_length=100)),
                ('estimated_outage_duration', models.CharField(choices=[('No Disruption (Default)', 'No Disruption (Default)'), ('1 to 50 msec', '1 to 50 msec'), ('51 msec to 1 min', '51 msec to 1 min'), ('1 min to 5 min', '1 min to 5 min'), ('1 min to 10 min', '1 min to 10 min'), ('1 min to 15 min', '1 min to 15 min'), ('10 min to 30 min', '10 min to 30 min'), ('30 min to 1 hour', '30 min to 1 hour'), ('1 hour to 2 hours', '1 hour to 2 hours'), ('1 hour to 3 hours', '1 hour to 3 hours'), ('1 hour to 4 hours', '1 hour to 4 hours'), ('1 hour to 5 hours', '1 hour to 5 hours'), ('1 hour to 6 hours', '1 hour to 6 hours'), ('1 hour to 7 hours', '1 hour to 7 hours'), ('1 hour to 8 hours', '1 hour to 8 hours')], max_length=100)),
                ('operational_categorization_1', models.CharField(choices=[('Customer', 'Customer'), ('IT', 'IT'), ('Hosting', 'Hosting')], max_length=100)),
                ('operational_categorization_2', models.CharField(choices=[('Internal', 'Internal'), ('OS Patch/Agent Upgrade', 'OS Patch/Agent Upgrade'), ('Hosting Network Services', 'Hosting Network Services')], max_length=100)),
                ('service_impact_assessment_work_info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CRQ Properties',
                'verbose_name_plural': 'CRQ Properties',
                'db_table': 'crq_properties',
                'ordering': ['change_type', 'manager_group'],
            },
        ),
    ]
