# Generated by Django 5.2.7 on 2025-12-17 10:20

import Customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('contact_person_name', models.CharField(max_length=30)),
                ('contact_person_email', models.EmailField(max_length=254)),
                ('contact_person_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('confluence_page_link', models.URLField(blank=True, null=True)),
                ('customer_webpage', models.URLField(blank=True, null=True)),
                ('customer_logo', models.ImageField(blank=True, null=True, upload_to=Customer.models.customer_logo_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='customers_name_25d5e3_idx'), models.Index(fields=['contact_person_email'], name='customers_contact_25fb08_idx')],
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_customer_name')],
            },
        ),
    ]
