-- Table: auth_permission
-- Mode: IN-PLACE
-- Backup Date: 2026-05-15 08:46:14
-- Row Count: 116
-- Hash: 124fef9785f456eb50a852693fa61cbc

DROP TABLE IF EXISTS auth_permission;
CREATE TABLE "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);

INSERT INTO auth_permission VALUES (1, 1, 'add_logentry', 'Can add log entry');
INSERT INTO auth_permission VALUES (2, 1, 'change_logentry', 'Can change log entry');
INSERT INTO auth_permission VALUES (3, 1, 'delete_logentry', 'Can delete log entry');
INSERT INTO auth_permission VALUES (4, 1, 'view_logentry', 'Can view log entry');
INSERT INTO auth_permission VALUES (5, 2, 'add_permission', 'Can add permission');
INSERT INTO auth_permission VALUES (6, 2, 'change_permission', 'Can change permission');
INSERT INTO auth_permission VALUES (7, 2, 'delete_permission', 'Can delete permission');
INSERT INTO auth_permission VALUES (8, 2, 'view_permission', 'Can view permission');
INSERT INTO auth_permission VALUES (9, 3, 'add_group', 'Can add group');
INSERT INTO auth_permission VALUES (10, 3, 'change_group', 'Can change group');
INSERT INTO auth_permission VALUES (11, 3, 'delete_group', 'Can delete group');
INSERT INTO auth_permission VALUES (12, 3, 'view_group', 'Can view group');
INSERT INTO auth_permission VALUES (13, 4, 'add_user', 'Can add user');
INSERT INTO auth_permission VALUES (14, 4, 'change_user', 'Can change user');
INSERT INTO auth_permission VALUES (15, 4, 'delete_user', 'Can delete user');
INSERT INTO auth_permission VALUES (16, 4, 'view_user', 'Can view user');
INSERT INTO auth_permission VALUES (17, 5, 'add_contenttype', 'Can add content type');
INSERT INTO auth_permission VALUES (18, 5, 'change_contenttype', 'Can change content type');
INSERT INTO auth_permission VALUES (19, 5, 'delete_contenttype', 'Can delete content type');
INSERT INTO auth_permission VALUES (20, 5, 'view_contenttype', 'Can view content type');
INSERT INTO auth_permission VALUES (21, 6, 'add_session', 'Can add session');
INSERT INTO auth_permission VALUES (22, 6, 'change_session', 'Can change session');
INSERT INTO auth_permission VALUES (23, 6, 'delete_session', 'Can delete session');
INSERT INTO auth_permission VALUES (24, 6, 'view_session', 'Can view session');
INSERT INTO auth_permission VALUES (25, 7, 'add_role', 'Can add Role');
INSERT INTO auth_permission VALUES (26, 7, 'change_role', 'Can change Role');
INSERT INTO auth_permission VALUES (27, 7, 'delete_role', 'Can delete Role');
INSERT INTO auth_permission VALUES (28, 7, 'view_role', 'Can view Role');
INSERT INTO auth_permission VALUES (29, 8, 'add_location', 'Can add Location');
INSERT INTO auth_permission VALUES (30, 8, 'change_location', 'Can change Location');
INSERT INTO auth_permission VALUES (31, 8, 'delete_location', 'Can delete Location');
INSERT INTO auth_permission VALUES (32, 8, 'view_location', 'Can view Location');
INSERT INTO auth_permission VALUES (33, 9, 'add_employee', 'Can add Employee');
INSERT INTO auth_permission VALUES (34, 9, 'change_employee', 'Can change Employee');
INSERT INTO auth_permission VALUES (35, 9, 'delete_employee', 'Can delete Employee');
INSERT INTO auth_permission VALUES (36, 9, 'view_employee', 'Can view Employee');
INSERT INTO auth_permission VALUES (37, 10, 'add_customer', 'Can add Customer');
INSERT INTO auth_permission VALUES (38, 10, 'change_customer', 'Can change Customer');
INSERT INTO auth_permission VALUES (39, 10, 'delete_customer', 'Can delete Customer');
INSERT INTO auth_permission VALUES (40, 10, 'view_customer', 'Can view Customer');
INSERT INTO auth_permission VALUES (41, 11, 'add_project', 'Can add Project');
INSERT INTO auth_permission VALUES (42, 11, 'change_project', 'Can change Project');
INSERT INTO auth_permission VALUES (43, 11, 'delete_project', 'Can delete Project');
INSERT INTO auth_permission VALUES (44, 11, 'view_project', 'Can view Project');
INSERT INTO auth_permission VALUES (45, 12, 'add_version', 'Can add Version');
INSERT INTO auth_permission VALUES (46, 12, 'change_version', 'Can change Version');
INSERT INTO auth_permission VALUES (47, 12, 'delete_version', 'Can delete Version');
INSERT INTO auth_permission VALUES (48, 12, 'view_version', 'Can view Version');
INSERT INTO auth_permission VALUES (49, 13, 'add_coordinationandexecutionescalation', 'Can add Coordination and Execution Escalation');
INSERT INTO auth_permission VALUES (50, 13, 'change_coordinationandexecutionescalation', 'Can change Coordination and Execution Escalation');
INSERT INTO auth_permission VALUES (51, 13, 'delete_coordinationandexecutionescalation', 'Can delete Coordination and Execution Escalation');
INSERT INTO auth_permission VALUES (52, 13, 'view_coordinationandexecutionescalation', 'Can view Coordination and Execution Escalation');
INSERT INTO auth_permission VALUES (53, 14, 'add_contactus', 'Can add Contact Us');
INSERT INTO auth_permission VALUES (54, 14, 'change_contactus', 'Can change Contact Us');
INSERT INTO auth_permission VALUES (55, 14, 'delete_contactus', 'Can delete Contact Us');
INSERT INTO auth_permission VALUES (56, 14, 'view_contactus', 'Can view Contact Us');
INSERT INTO auth_permission VALUES (57, 15, 'add_accesscontrol_role', 'Can add Access Control Role');
INSERT INTO auth_permission VALUES (58, 15, 'change_accesscontrol_role', 'Can change Access Control Role');
INSERT INTO auth_permission VALUES (59, 15, 'delete_accesscontrol_role', 'Can delete Access Control Role');
INSERT INTO auth_permission VALUES (60, 15, 'view_accesscontrol_role', 'Can view Access Control Role');
INSERT INTO auth_permission VALUES (61, 16, 'add_accesscontrol_employee', 'Can add Access Control Employee');
INSERT INTO auth_permission VALUES (62, 16, 'change_accesscontrol_employee', 'Can change Access Control Employee');
INSERT INTO auth_permission VALUES (63, 16, 'delete_accesscontrol_employee', 'Can delete Access Control Employee');
INSERT INTO auth_permission VALUES (64, 16, 'view_accesscontrol_employee', 'Can view Access Control Employee');
INSERT INTO auth_permission VALUES (65, 17, 'add_changedetails', 'Can add Change Detail');
INSERT INTO auth_permission VALUES (66, 17, 'change_changedetails', 'Can change Change Detail');
INSERT INTO auth_permission VALUES (67, 17, 'delete_changedetails', 'Can delete Change Detail');
INSERT INTO auth_permission VALUES (68, 17, 'view_changedetails', 'Can view Change Detail');
INSERT INTO auth_permission VALUES (69, 18, 'add_task_information', 'Can add task information');
INSERT INTO auth_permission VALUES (70, 18, 'change_task_information', 'Can change task information');
INSERT INTO auth_permission VALUES (71, 18, 'delete_task_information', 'Can delete task information');
INSERT INTO auth_permission VALUES (72, 18, 'view_task_information', 'Can view task information');
INSERT INTO auth_permission VALUES (73, 19, 'add_clients', 'Can add Client');
INSERT INTO auth_permission VALUES (74, 19, 'change_clients', 'Can change Client');
INSERT INTO auth_permission VALUES (75, 19, 'delete_clients', 'Can delete Client');
INSERT INTO auth_permission VALUES (76, 19, 'view_clients', 'Can view Client');
INSERT INTO auth_permission VALUES (77, 20, 'add_crqadditionaltask', 'Can add CRQ Additional Task');
INSERT INTO auth_permission VALUES (78, 20, 'change_crqadditionaltask', 'Can change CRQ Additional Task');
INSERT INTO auth_permission VALUES (79, 20, 'delete_crqadditionaltask', 'Can delete CRQ Additional Task');
INSERT INTO auth_permission VALUES (80, 20, 'view_crqadditionaltask', 'Can view CRQ Additional Task');
INSERT INTO auth_permission VALUES (81, 21, 'add_crqclientapproval', 'Can add CRQ Client Approval');
INSERT INTO auth_permission VALUES (82, 21, 'change_crqclientapproval', 'Can change CRQ Client Approval');
INSERT INTO auth_permission VALUES (83, 21, 'delete_crqclientapproval', 'Can delete CRQ Client Approval');
INSERT INTO auth_permission VALUES (84, 21, 'view_crqclientapproval', 'Can view CRQ Client Approval');
INSERT INTO auth_permission VALUES (85, 22, 'add_crqcoordination', 'Can add CRQ Coordination');
INSERT INTO auth_permission VALUES (86, 22, 'change_crqcoordination', 'Can change CRQ Coordination');
INSERT INTO auth_permission VALUES (87, 22, 'delete_crqcoordination', 'Can delete CRQ Coordination');
INSERT INTO auth_permission VALUES (88, 22, 'view_crqcoordination', 'Can view CRQ Coordination');
INSERT INTO auth_permission VALUES (89, 23, 'add_crqproperties', 'Can add CRQ Properties');
INSERT INTO auth_permission VALUES (90, 23, 'change_crqproperties', 'Can change CRQ Properties');
INSERT INTO auth_permission VALUES (91, 23, 'delete_crqproperties', 'Can delete CRQ Properties');
INSERT INTO auth_permission VALUES (92, 23, 'view_crqproperties', 'Can view CRQ Properties');
INSERT INTO auth_permission VALUES (93, 24, 'add_dcregion', 'Can add DC Region');
INSERT INTO auth_permission VALUES (94, 24, 'change_dcregion', 'Can change DC Region');
INSERT INTO auth_permission VALUES (95, 24, 'delete_dcregion', 'Can delete DC Region');
INSERT INTO auth_permission VALUES (96, 24, 'view_dcregion', 'Can view DC Region');
INSERT INTO auth_permission VALUES (97, 25, 'add_uploaderproject', 'Can add Uploader Project');
INSERT INTO auth_permission VALUES (98, 25, 'change_uploaderproject', 'Can change Uploader Project');
INSERT INTO auth_permission VALUES (99, 25, 'delete_uploaderproject', 'Can delete Uploader Project');
INSERT INTO auth_permission VALUES (100, 25, 'view_uploaderproject', 'Can view Uploader Project');
INSERT INTO auth_permission VALUES (101, 26, 'add_uploadervariant', 'Can add Uploader Variant');
INSERT INTO auth_permission VALUES (102, 26, 'change_uploadervariant', 'Can change Uploader Variant');
INSERT INTO auth_permission VALUES (103, 26, 'delete_uploadervariant', 'Can delete Uploader Variant');
INSERT INTO auth_permission VALUES (104, 26, 'view_uploadervariant', 'Can view Uploader Variant');
INSERT INTO auth_permission VALUES (105, 27, 'add_timezonetable', 'Can add Timezone');
INSERT INTO auth_permission VALUES (106, 27, 'change_timezonetable', 'Can change Timezone');
INSERT INTO auth_permission VALUES (107, 27, 'delete_timezonetable', 'Can delete Timezone');
INSERT INTO auth_permission VALUES (108, 27, 'view_timezonetable', 'Can view Timezone');
INSERT INTO auth_permission VALUES (109, 28, 'add_aipdata', 'Can add AIP Data');
INSERT INTO auth_permission VALUES (110, 28, 'change_aipdata', 'Can change AIP Data');
INSERT INTO auth_permission VALUES (111, 28, 'delete_aipdata', 'Can delete AIP Data');
INSERT INTO auth_permission VALUES (112, 28, 'view_aipdata', 'Can view AIP Data');
INSERT INTO auth_permission VALUES (113, 29, 'add_serverdetails', 'Can add Server Detail');
INSERT INTO auth_permission VALUES (114, 29, 'change_serverdetails', 'Can change Server Detail');
INSERT INTO auth_permission VALUES (115, 29, 'delete_serverdetails', 'Can delete Server Detail');
INSERT INTO auth_permission VALUES (116, 29, 'view_serverdetails', 'Can view Server Detail');
