# Generated by Django 5.2.7 on 2026-05-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15)])),
                ('client', models.CharField(max_length=255)),
                ('server', models.CharField(max_length=255)),
                ('operating_system', models.CharField(blank=True, max_length=255, null=True)),
                ('application', models.CharField(blank=True, max_length=255, null=True)),
                ('environment', models.CharField(blank=True, max_length=255, null=True)),
                ('server_type', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('include', models.BooleanField(choices=[(True, 'True'), (False, 'False')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Server Detail',
                'verbose_name_plural': 'Server Details',
                'db_table': 'server_details',
                'ordering': ['batch', 'server'],
            },
        ),
    ]
