# Generated by Django 5.2.7 on 2026-05-20 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('uploader_projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrqClientApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clients')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader_projects.uploaderproject')),
            ],
            options={
                'verbose_name': 'CRQ Client Approval',
                'verbose_name_plural': 'CRQ Client Approvals',
                'db_table': 'crq_client_approval',
                'ordering': ['client', 'template'],
            },
        ),
    ]
