# Generated by Django 5.2.7 on 2025-12-10 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Location', '0001_initial'),
        ('Role', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('cuid', models.CharField(max_length=20, unique=True)),
                ('employee_code', models.CharField(max_length=20, unique=True)),
                ('designation', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('hired_date', models.DateField()),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='employees', to='Location.location')),
                ('manager_name', models.ForeignKey(blank=True, help_text='Optional direct manager (another employee).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='Employee.employee')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='employees', to='Role.role')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employees',
                'ordering': ['first_name', 'last_name'],
                'indexes': [models.Index(fields=['employee_code'], name='employees_employe_6fc092_idx'), models.Index(fields=['cuid'], name='employees_cuid_a1b441_idx'), models.Index(fields=['email'], name='employees_email_f66e96_idx')],
            },
        ),
    ]
