# Generated by Django 5.2.7 on 2026-05-11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploaderProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(max_length=100)),
                ('project_id', models.CharField(max_length=100)),
                ('project_title', models.CharField(max_length=255)),
                ('project', models.CharField(max_length=255)),
                ('change_title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Uploader Project',
                'verbose_name_plural': 'Uploader Projects',
                'db_table': 'uploader_projects',
                'ordering': ['template_id', 'project_id'],
            },
        ),
    ]
