# Generated by Django 5.2.7 on 2026-05-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrqCoordination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordination', models.CharField(max_length=100)),
                ('coordinator_company', models.CharField(max_length=100)),
                ('coordinator_organization', models.CharField(max_length=100)),
                ('workgroup', models.CharField(max_length=100)),
                ('change_coordinator', models.CharField(max_length=100)),
                ('task_name', models.CharField(blank=True, max_length=100, null=True)),
                ('task_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CRQ Coordination',
                'verbose_name_plural': 'CRQ Coordinations',
                'db_table': 'crq_coordination',
                'ordering': ['coordination', 'workgroup'],
            },
        ),
    ]
