apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rmtestproject
  labels:
    app.kubernetes.io/name: rmtestproject
    app.kubernetes.io/part-of: rmtestproject-project
    kubernetes.azure.com/generator: devhub
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rmtestproject
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80