# Generated by Django 5.2.7 on 2026-05-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('vantive_name', models.CharField(max_length=100)),
                ('site_id', models.CharField(max_length=100)),
                ('advanced_essential', models.CharField(choices=[('Advanced', 'Advanced'), ('Essential', 'Essential')], max_length=20)),
                ('start_week', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth'), ('Penultimate', 'Penultimate'), ('Last', 'Last'), ('Specific Date', 'Specific Date'), ('First Weekday', 'First Weekday')], max_length=20)),
                ('start_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Specific Date', 'Specific Date'), ('First Weekday', 'First Weekday')], max_length=20)),
                ('specific_date', models.DateField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('Monthly', 'Monthly'), ('Bi-Monthly', 'Bi-Monthly'), ('Quarterly', 'Quarterly'), ('Request', 'Request')], max_length=20)),
                ('add_month', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('ask_for_approval_in_email', models.BooleanField(default=False)),
                ('email_greeting', models.CharField(blank=True, max_length=255, null=True)),
                ('email_to', models.CharField(blank=True, max_length=255, null=True)),
                ('email_cc', models.CharField(blank=True, max_length=255, null=True)),
                ('email_bcc', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'clients',
                'ordering': ['client_name'],
                'indexes': [models.Index(fields=['client_name'], name='clients_client__3f3dca_idx'), models.Index(fields=['site_id'], name='clients_site_id_065b3a_idx'), models.Index(fields=['frequency'], name='clients_frequen_1a6b26_idx'), models.Index(fields=['vantive_name'], name='clients_vantive_c47345_idx'), models.Index(fields=['is_active'], name='clients_is_acti_43299d_idx')],
            },
        ),
    ]
