# Generated by Django 5.2.7 on 2026-05-11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploaderVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('project', models.CharField(max_length=255)),
                ('variant_name', models.CharField(max_length=255)),
                ('variant_description', models.TextField(blank=True, null=True)),
                ('default_variant', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('impacting', models.BooleanField(default=False)),
                ('mop', models.TextField(blank=True, null=True)),
                ('team_name', models.CharField(blank=True, max_length=255, null=True)),
                ('team_description', models.TextField(blank=True, null=True)),
                ('variant', models.CharField(blank=True, max_length=255, null=True)),
                ('default_project_variant', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Uploader Variant',
                'verbose_name_plural': 'Uploader Variants',
                'db_table': 'uploader_variants',
                'ordering': ['template_id', 'variant_name'],
            },
        ),
    ]
