# Generated by Django 5.2.7 on 2026-02-26 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Changedetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='task_information',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('server_name', models.CharField(max_length=100)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('environment', models.CharField(blank=True, max_length=100, null=True)),
                ('environment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('stage', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('started_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('manual_status', models.CharField(blank=True, max_length=100, null=True)),
                ('change_number', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='taskinformations', to='Changedetails.changedetails')),
            ],
            options={
                'verbose_name': 'task information',
                'verbose_name_plural': 'task information',
                'db_table': 'task_information',
                'ordering': ['-updated_date', '-started_date'],
                'indexes': [models.Index(fields=['change_number'], name='task_inform_change__eae921_idx')],
            },
        ),
    ]
