# Generated by Django 5.2.7 on 2025-12-10 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employee', '0001_initial'),
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinationAndExecutionEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(unique=True)),
                ('description', models.CharField(max_length=255)),
                ('contact_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employees', models.ManyToManyField(related_name='escalations', to='Employee.employee')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='escalations', to='Location.location')),
            ],
            options={
                'verbose_name': 'Coordination and Execution Escalation',
                'verbose_name_plural': 'Coordination and Execution Escalations',
                'db_table': 'coordination_and_execution_escalations',
                'ordering': ['level'],
                'indexes': [models.Index(fields=['level'], name='coordinatio_level_d75ce7_idx'), models.Index(fields=['location'], name='coordinatio_locatio_964fe4_idx')],
            },
        ),
    ]
