# Generated by Django 5.2.7 on 2025-12-10 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Role', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControl_Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=200)),
                ('can_view', models.BooleanField(default=False)),
                ('can_add', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Role.role')),
            ],
            options={
                'verbose_name': 'Access Control Role',
                'verbose_name_plural': 'Access Control Roles',
                'db_table': 'accesscontrol_role',
                'unique_together': {('role', 'app_name')},
            },
        ),
    ]
