# Generated by Django 5.2.7 on 2026-05-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimezoneTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_zone', models.CharField(max_length=100)),
                ('remedy_tz_dst_inactive', models.CharField(blank=True, max_length=50, null=True)),
                ('remedy_tz_dst_active', models.CharField(blank=True, max_length=50, null=True)),
                ('non_dst_offset_hours', models.CharField(blank=True, max_length=20, null=True)),
                ('dst_offset', models.CharField(blank=True, max_length=20, null=True)),
                ('offset_mins', models.CharField(blank=True, max_length=20, null=True)),
                ('dst_start_time', models.CharField(blank=True, max_length=50, null=True)),
                ('dst_end_time', models.CharField(blank=True, max_length=50, null=True)),
                ('utc_offset', models.CharField(blank=True, max_length=20, null=True)),
                ('daylight_savings_start', models.CharField(blank=True, max_length=100, null=True)),
                ('daylight_savings_end', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Timezone',
                'verbose_name_plural': 'Timezones',
                'db_table': 'timezone_table',
                'ordering': ['time_zone'],
            },
        ),
    ]
