# Generated by Django 5.2.7 on 2026-05-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AipData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(blank=True, max_length=255, null=True)),
                ('inst_comp_name', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('inst_comp_status', models.CharField(blank=True, max_length=100, null=True)),
                ('aip_status', models.CharField(blank=True, max_length=100, null=True)),
                ('vpdc_profile', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_site_id', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('physical_site_id', models.CharField(blank=True, max_length=100, null=True)),
                ('support_region', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_product_line', models.CharField(blank=True, max_length=255, null=True)),
                ('service_package', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AIP Data',
                'verbose_name_plural': 'AIP Data',
                'db_table': 'aip_data',
                'ordering': ['server'],
            },
        ),
    ]
