# Generated by Django 5.2.7 on 2025-12-10 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_system', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=10)),
                ('policy_name', models.CharField(max_length=100, unique=True)),
                ('manual_file_name', models.CharField(max_length=100)),
                ('manual_file_location', models.CharField(max_length=100)),
                ('confluence_page_link', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='versions', to='Project.project')),
            ],
            options={
                'verbose_name': 'Version',
                'verbose_name_plural': 'Versions',
                'db_table': 'versions',
                'ordering': ['project', '-version', 'operation_system'],
                'indexes': [models.Index(fields=['policy_name'], name='versions_policy__11b246_idx'), models.Index(fields=['project', 'operation_system', 'version'], name='versions_project_9aaf5f_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'operation_system', 'version', 'policy_name'), name='unique_project_os_version_policy_name')],
            },
        ),
    ]
