# Generated by Django 5.2.7 on 2026-05-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrqAdditionalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('summary', models.TextField(blank=True, null=True)),
                ('assignee', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CRQ Additional Task',
                'verbose_name_plural': 'CRQ Additional Tasks',
                'db_table': 'crq_additional_tasks',
                'ordering': ['task_name'],
                'indexes': [models.Index(fields=['task_name'], name='crq_additio_task_na_6aaea8_idx'), models.Index(fields=['assignee'], name='crq_additio_assigne_335ded_idx')],
            },
        ),
    ]
