import os, requests,datetime,sqlite3

conn = sqlite3.connect('db.sqlite3')
cursor = conn.cursor()
cursor.execute("DELETE FROM clients")
cursor.execute("INSERT INTO clients(client_name, vantive_name, site_id, advanced_essential, start_week, start_day, specific_date, frequency, add_month, notes, ask_for_approval_in_email, email_greeting, email_to, email_cc, email_bcc, is_active,created_at,updated_at) VALUES ('Savvis__Itential', 'Savvis', 'UNKNOWN', 'Essential', 'First', 'Monday', '', 'Quarterly', '', '','','', 'David.Moore3@lumen.com,David.Stamper@lumen.com,Gurdyal.Singh@lumen.com,Jason.Patrick2@lumen.com,Seethalakshmi.Balachandran@lumen.com,ManagedServicesToolsApplicationSupport@centurylink.com,nick.havard@lumen.com', 'bruce.robertson@lumen.com', '', 1,'2026-05-11 05:51:06.311683','2026-05-11 05:51:06.311683')")
cursor.execute("INSERT INTO clients(client_name, vantive_name, site_id, advanced_essential, start_week, start_day, specific_date, frequency, add_month, notes, ask_for_approval_in_email, email_greeting, email_to, email_cc, email_bcc, is_active,created_at,updated_at) VALUES ('Savvis__HIE-Platform_PCI', 'Savvis', 'UNKNOWN', 'Essential', 'First', 'Monday', '', 'Monthly', '', '','','', 'David.Moore3@lumen.com,David.Stamper@lumen.com,Gurdyal.Singh@lumen.com,Jason.Patrick2@lumen.com,Seethalakshmi.Balachandran@lumen.com,ManagedServicesToolsApplicationSupport@centurylink.com,nick.havard@lumen.com', 'bruce.robertson@lumen.com', '', 1,'2026-05-11 05:51:06.311683','2026-05-11 05:51:06.311683')")
cursor.execute("INSERT INTO clients(client_name, vantive_name, site_id, advanced_essential, start_week, start_day, specific_date, frequency, add_month, notes, ask_for_approval_in_email, email_greeting, email_to, email_cc, email_bcc, is_active,created_at,updated_at) VALUES ('Savvis__HPNA', 'Savvis', 'UNKNOWN', 'Essential', 'First', 'Monday', '', 'Quarterly', '', '', '', '', '', '', '', 1,'2026-05-11 05:51:06.311683','2026-05-11 05:51:06.311683')")
cursor.execute("INSERT INTO clients(client_name, vantive_name, site_id, advanced_essential, start_week, start_day, specific_date, frequency, add_month, notes, ask_for_approval_in_email, email_greeting, email_to, email_cc, email_bcc, is_active,created_at,updated_at) VALUES ('Savvis__HPSA', 'Savvis', 'UNKNOWN', 'Essential', 'First', 'Monday', '', 'Quarterly', '', '', '', '', '', '', '', 1,'2026-05-11 05:51:06.311683','2026-05-11 05:51:06.311683')")
cursor.execute("INSERT INTO clients(client_name, vantive_name, site_id, advanced_essential, start_week, start_day, specific_date, frequency, add_month, notes, ask_for_approval_in_email, email_greeting, email_to, email_cc, email_bcc, is_active,created_at,updated_at) VALUES ('Savvis__ActiveMQ', 'Savvis', 'UNKNOWN', 'Essential', 'First', 'Monday', '', 'Quarterly', '', '', '', '', '', '', '', 1,'2026-05-11 05:51:06.311683','2026-05-11 05:51:06.311683')")
cursor.execute("INSERT INTO clients(client_name, vantive_name, site_id, advanced_essential, start_week, start_day, specific_date, frequency, add_month, notes, ask_for_approval_in_email, email_greeting, email_to, email_cc, email_bcc, is_active,created_at,updated_at) VALUES ('Savvis__OO', 'Savvis', 'UNKNOWN', 'Essential', 'First', 'Monday', '', 'Quarterly', '', '', '', '', '', '', '', 1,'2026-05-11 05:51:06.311683','2026-05-11 05:51:06.311683')")
conn.commit()