import sqlite3

conn = sqlite3.connect('uploader.sqlite3')
cursor = conn.cursor()
cursor.execute("create table if not exists  uploader_crq_properties(id integer primary key autoincrement, is_impacting text, change_type text, manager_group text, class text, impact text, urgency text, risk_level text, estimated_outage_duration text, operational_categorization_1 text, operational_categorization_2 text, service_impact_assessment_work_info text)")
conn.commit()
cursor.execute("INSERT INTO uploader_crq_properties(is_impacting, change_type, manager_group, class, impact, urgency, risk_level, estimated_outage_duration, operational_categorization_1, operational_categorization_2, service_impact_assessment_work_info) VALUES ('TRUE', 'Service / Normal Maintenance', 'Infra Change', 'No Impact', '2-Significant/Large', '4-Low', 'Risk Level 3', '1 hour to 6 hours', 'IT', 'Internal', 'System health checks have been performed via environment audits and no redundancy and resiliency assessment is required for localised agent upgrades')")
cursor.execute("INSERT INTO uploader_crq_properties(is_impacting, change_type, manager_group, class, impact, urgency, risk_level, estimated_outage_duration, operational_categorization_1, operational_categorization_2, service_impact_assessment_work_info) VALUES ('TRUE', 'Customer Change', 'Client Change', 'Standard', '2-Significant/Large', '4-Low', 'Risk Level 3', '1 hour to 4 hours', 'Customer', 'OS Patch/Agent Upgrade', '')")
cursor.execute("INSERT INTO uploader_crq_properties(is_impacting, change_type, manager_group, class, impact, urgency, risk_level, estimated_outage_duration, operational_categorization_1, operational_categorization_2, service_impact_assessment_work_info) VALUES ('TRUE', 'Emergency Maintenance', 'Infra Change', 'Emergency', '1-Extensive/Widespread', '2-High', 'Risk Level 1', '1 hour to 4 hours', 'Hosting', 'Hosting Network Services', 'System health checks have been performed via environment audits and no redundancy and resiliency assessment is required for localised agent upgrades')")
cursor.execute("INSERT INTO uploader_crq_properties(is_impacting, change_type, manager_group, class, impact, urgency, risk_level, estimated_outage_duration, operational_categorization_1, operational_categorization_2, service_impact_assessment_work_info) VALUES ('FALSE', 'Service / Normal Maintenance', 'Infra Change', 'No Impact', '4-Minor/Localized', '4-Low', 'Risk Level 3', 'No Disruption (Default)', 'IT', 'Internal', 'System health checks have been performed via environment audits and no kernel upgrade or reboot will occur')")
cursor.execute("INSERT INTO uploader_crq_properties(is_impacting, change_type, manager_group, class, impact, urgency, risk_level, estimated_outage_duration, operational_categorization_1, operational_categorization_2, service_impact_assessment_work_info) VALUES ('FALSE', 'Customer Change', 'Client Change', 'Standard', '4-Minor/Localized', '4-Low', 'Risk Level 3', 'No Disruption (Default)', 'Customer', 'OS Patch/Agent Upgrade', '')")
cursor.execute("INSERT INTO uploader_crq_properties(is_impacting, change_type, manager_group, class, impact, urgency, risk_level, estimated_outage_duration, operational_categorization_1, operational_categorization_2, service_impact_assessment_work_info) VALUES ('FALSE', 'Emergency Maintenance', 'Infra Change', 'Emergency', '1-Extensive/Widespread', '2-High', 'Risk Level 3', 'No Disruption (Default)', 'Hosting', 'Hosting Network Services', 'System health checks have been performed via environment audits and no redundancy and resiliency assessment is required for localised agent upgrades')")
conn.commit()